export const ADD_QUESTIONS_ATTEMPT = 'ADD_QUESTIONS_ATTEMPT';
export const ADD_QUESTIONS_SUCCESS = 'ADD_QUESTIONS_SUCCESS';
export const ADD_QUESTIONS_ERROR = 'ADD_QUESTIONS_ERROR';
export const RESQUEST_POINTS_POSITION_SCREEN_A_ATTEMPT = 'RESQUEST_POINTS_POSITION_SCREEN_A_ATTEMPT';
export const RESQUEST_POINTS_POSITION_SCREEN_A_SUCCESS = 'RESQUEST_POINTS_POSITION_SCREEN_A_SUCCESS';
export const RESQUEST_POINTS_POSITION_SCREEN_A_ERROR = 'RESQUEST_POINTS_POSITION_SCREEN_A_ERROR';
export const SCREEN_A_COMPLETED = 'SCREEN_A_COMPLETED';
export const SCREEN_A_NEXT_QUESTION = 'SCREEN_A_NEXT_QUESTION';
